package com.itheima.takeout.db.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.itheima.takeout.db.greendao.CartGoods;

import com.itheima.takeout.db.greendao.CartGoodsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cartGoodsDaoConfig;

    private final CartGoodsDao cartGoodsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cartGoodsDaoConfig = daoConfigMap.get(CartGoodsDao.class).clone();
        cartGoodsDaoConfig.initIdentityScope(type);

        cartGoodsDao = new CartGoodsDao(cartGoodsDaoConfig, this);

        registerDao(CartGoods.class, cartGoodsDao);
    }
    
    public void clear() {
        cartGoodsDaoConfig.getIdentityScope().clear();
    }

    public CartGoodsDao getCartGoodsDao() {
        return cartGoodsDao;
    }

}
